In [1]:
import numpy as np

import matplotlib.pyplot as plt



In [2]:
from pathlib import Path
print(Path.cwd())

/Users/johngracious/Documents/Documents - John’s MacBook Pro/GitHub/Spacecraft-Dynamics-and-Control/Studies/pvt_study


In [3]:
import sys
sys.path.insert(0, r"../../")
import AttitudeKinematicsLib as ak
print("Contents of AttitudeKinematicsLib:")
for name in sorted(dir(ak)):
    if not name.startswith("_"):
        print(name)

Contents of AttitudeKinematicsLib:
BInvmat_CRP
BInvmat_EP
BInvmat_Euler
BInvmat_MRP
BInvmat_PRV
Bmat_CRP
Bmat_EP
Bmat_Euler
Bmat_MRP
Bmat_PRV
CRP
CRP_to_DCM
DCM_to_CRP
DCM_to_EP
DCM_to_Euler
DCM_to_MRP
DCM_to_PRV
DCM_utils
EP_to_DCM
EulerAngles
EulerRodriguesParameters
Euler_to_DCM
MRP
MRP_compose
MRP_shadow
MRP_to_DCM
PRV
PRV_to_DCM
integrate_quaternion
normalize_quat
np
quat_derivative
quat_diff
quat_inv
quat_mult
rotation_matrix_x
rotation_matrix_y
rotation_matrix_z
skew_symmetric
solve_ivp
validate_DCM
validate_vec3
validate_vec4


In [4]:
# Question 2
q_A = np.array([0.5, 0.5, 0.5, -0.5])
q_B = np.array([-0.5, -0.5, -0.5, 0.5])

C_A = ak.EP_to_DCM(q_A)
C_B = ak.EP_to_DCM(q_B)

prv_A = ak.DCM_to_PRV(C_A)
prv_B = ak.DCM_to_PRV(C_B)

print("Question 2:")
print("q_A:", q_A)
print("q_B:", q_B)
print("DCM for q_A:\n", C_A)
print("DCM for q_B:\n", C_B)
print("PRV for q_A:", prv_A)
print("PRV for q_B:", prv_B)

Question 2:
q_A: [ 0.5  0.5  0.5 -0.5]
q_B: [-0.5 -0.5 -0.5  0.5]
DCM for q_A:
 [[ 0.  0. -1.]
 [ 1.  0.  0.]
 [ 0. -1.  0.]]
DCM for q_B:
 [[ 0.  0. -1.]
 [ 1.  0.  0.]
 [ 0. -1.  0.]]
PRV for q_A: (array([ 0.57735027,  0.57735027, -0.57735027]), 120.00000000000001)
PRV for q_B: (array([ 0.57735027,  0.57735027, -0.57735027]), 120.00000000000001)
